on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.2

      - name: Publish
        run: gradle check publish --no-configure-on-demand --no-daemon
        env:
          ORG_GRADLE_PROJECT_githubUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPassword: ${{ github.token }}
